2021-09-30 20:54:57,040 INFO    MainThread:35227 [wandb_setup.py:_flush():69] setting env: {}
2021-09-30 20:54:57,040 INFO    MainThread:35227 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-30 20:54:57,040 INFO    MainThread:35227 [wandb_init.py:_log_setup():348] Logging user logs to /opt/ml/detection/mmdetection/boostcamp/notebook/wandb/run-20210930_205457-3fbmszdv/logs/debug.log
2021-09-30 20:54:57,040 INFO    MainThread:35227 [wandb_init.py:_log_setup():349] Logging internal logs to /opt/ml/detection/mmdetection/boostcamp/notebook/wandb/run-20210930_205457-3fbmszdv/logs/debug-internal.log
2021-09-30 20:54:57,041 INFO    MainThread:35227 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1837545110>
2021-09-30 20:54:57,041 INFO    MainThread:35227 [wandb_init.py:init():381] calling init triggers
2021-09-30 20:54:57,041 INFO    MainThread:35227 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-30 20:54:57,041 INFO    MainThread:35227 [wandb_init.py:init():430] starting backend
2021-09-30 20:54:57,041 INFO    MainThread:35227 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-30 20:54:57,078 INFO    MainThread:35227 [backend.py:ensure_launched():135] starting backend process...
2021-09-30 20:54:57,121 INFO    MainThread:35227 [backend.py:ensure_launched():140] started backend process with pid: 35304
2021-09-30 20:54:57,122 INFO    MainThread:35227 [wandb_init.py:init():435] backend started and connected
2021-09-30 20:54:57,139 INFO    MainThread:35227 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-30 20:54:57,141 INFO    MainThread:35227 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-30 20:54:57,141 INFO    MainThread:35227 [wandb_init.py:init():494] updated telemetry
2021-09-30 20:54:57,141 INFO    MainThread:35227 [wandb_init.py:init():517] communicating current version
2021-09-30 20:54:57,833 INFO    MainThread:35227 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-30 20:54:57,834 INFO    MainThread:35227 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-30 20:54:58,071 INFO    MainThread:35227 [wandb_init.py:init():557] starting run threads in backend
2021-09-30 20:55:03,078 INFO    MainThread:35227 [wandb_run.py:_console_start():1605] atexit reg
2021-09-30 20:55:03,078 INFO    MainThread:35227 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-30 20:55:03,079 INFO    MainThread:35227 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-30 20:55:03,079 INFO    MainThread:35227 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-30 20:55:03,079 INFO    MainThread:35227 [wandb_init.py:init():582] run started, returning control to user process
2021-09-30 21:03:56,249 INFO    MainThread:35227 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-30 21:03:56,249 INFO    MainThread:35227 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/boostcamp/notebook/mm_vfNet_train.ipynb
2021-09-30 21:05:44,469 INFO    MainThread:35227 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-30 21:05:44,473 INFO    MainThread:35227 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-30 21:05:44,474 INFO    MainThread:35227 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/boostcamp/notebook/mm_vfNet_train.ipynb
2021-09-30 21:06:40,977 INFO    MainThread:35227 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-30 21:06:40,992 INFO    MainThread:35227 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-30 21:06:40,993 INFO    MainThread:35227 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/boostcamp/notebook/mm_vfNet_train.ipynb
2021-09-30 21:06:45,170 INFO    MainThread:35227 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-30 21:06:45,170 INFO    MainThread:35227 [wandb_run.py:_restore():1547] restore
