2021-09-28 09:08:06,208 INFO    MainThread:1761 [wandb_setup.py:_flush():69] setting env: {}
2021-09-28 09:08:06,208 INFO    MainThread:1761 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-28 09:08:06,208 INFO    MainThread:1761 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'c35b65a7f89f2f2b3960d0b0e6c47b437ef6abac'}
2021-09-28 09:08:06,208 INFO    MainThread:1761 [wandb_init.py:_log_setup():348] Logging user logs to /opt/ml/detection/mmdetection/wandb/run-20210928_090806-2wwun0bl/logs/debug.log
2021-09-28 09:08:06,208 INFO    MainThread:1761 [wandb_init.py:_log_setup():349] Logging internal logs to /opt/ml/detection/mmdetection/wandb/run-20210928_090806-2wwun0bl/logs/debug-internal.log
2021-09-28 09:08:06,209 INFO    MainThread:1761 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb702796790>
2021-09-28 09:08:06,210 INFO    MainThread:1761 [wandb_init.py:init():381] calling init triggers
2021-09-28 09:08:06,210 INFO    MainThread:1761 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-28 09:08:06,210 INFO    MainThread:1761 [wandb_init.py:init():430] starting backend
2021-09-28 09:08:06,210 INFO    MainThread:1761 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-28 09:08:06,282 INFO    MainThread:1761 [backend.py:ensure_launched():135] starting backend process...
2021-09-28 09:08:06,323 INFO    MainThread:1761 [backend.py:ensure_launched():140] started backend process with pid: 1921
2021-09-28 09:08:06,325 INFO    MainThread:1761 [wandb_init.py:init():435] backend started and connected
2021-09-28 09:08:06,345 INFO    MainThread:1761 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-28 09:08:06,346 INFO    MainThread:1761 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-28 09:08:06,346 INFO    MainThread:1761 [wandb_init.py:init():494] updated telemetry
2021-09-28 09:08:06,346 INFO    MainThread:1761 [wandb_init.py:init():517] communicating current version
2021-09-28 09:08:07,123 INFO    MainThread:1761 [wandb_init.py:init():522] got version response 
2021-09-28 09:08:07,123 INFO    MainThread:1761 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-28 09:08:12,412 INFO    MainThread:1761 [wandb_init.py:init():557] starting run threads in backend
2021-09-28 09:08:17,420 INFO    MainThread:1761 [wandb_run.py:_console_start():1605] atexit reg
2021-09-28 09:08:17,421 INFO    MainThread:1761 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-28 09:08:17,421 INFO    MainThread:1761 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-28 09:08:17,423 INFO    MainThread:1761 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-28 09:08:17,423 INFO    MainThread:1761 [wandb_init.py:init():582] run started, returning control to user process
2021-09-28 09:08:20,753 INFO    MainThread:1761 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-28 09:08:20,754 INFO    MainThread:1761 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/mm_faster_rcnn_train.ipynb
2021-09-28 09:11:35,990 INFO    MainThread:1761 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-28 09:11:39,785 INFO    MainThread:1761 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-28 09:11:39,785 INFO    MainThread:1761 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/mm_faster_rcnn_train.ipynb
2021-09-28 09:11:45,763 INFO    MainThread:1761 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-28 09:11:49,041 INFO    MainThread:1761 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-28 09:11:49,042 INFO    MainThread:1761 [jupyter.py:save_ipynb():301] looking for notebook: mmdetection/mm_faster_rcnn_train.ipynb
2021-09-28 09:11:54,358 INFO    MainThread:1761 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-28 09:11:54,359 INFO    MainThread:1761 [wandb_run.py:_restore():1547] restore
2021-09-28 09:11:55,204 INFO    MainThread:1761 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 151593
  total_bytes: 151593
}

